apiVersion: v1
kind: Pod
metadata:
  name: winpodfilemount
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: winpodfilemount
    image: coolstercodes.azurecr.io/windowspodfilemount:v1.0.0
    args: ["C:\\hostfilemount\\config"]
    volumeMounts:
      - name: hostfilemount
        mountPath: /hostfilemount
  volumes:
    - name: hostfilemount
      hostPath:
        path: /k
        type: Directory
