name: sorg CI

env:
  # Saw build failures, apparently because awscli is trying to determine
  # region. This is an undocumented env var that disables that check.
  #
  # Discovered from: https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
  AWS_EC2_METADATA_DISABLED: true

  CONCURRENCY: 10 # reduced because I think I'm running into Dropbox rate problems

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Once a week on Tuesday.
    - cron: "0 0 * * TUE"

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "go env GOPATH=$(go env GOPATH)"
          echo "pwd=$(pwd)"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "HOME=${HOME}"

      - name: Clean
        run: make clean

      - name: "Go: Install"
        run: make install

      - name: "Go: Test"
        run: make test

      - name: "Check: Gofmt"
        run: make check-gofmt

      - name: "Check: Markdown headers"
        run: make check-headers

  check_tailwind:
    runs-on: macos-latest
    timeout-minutes: 3

    env:
      TAILWIND_VERSION: v3.4.15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${{ env.TAILWIND_VERSION }}/tailwindcss-macos-arm64
          mv tailwindcss-macos-arm64 tailwindcss
          chmod +x tailwindcss

      - name: Generate Tailwind
        run: |
          ./tailwindcss -i ./content/stylesheets/tailwind_base.css -o ./content/stylesheets/tailwind.css
          ./tailwindcss -i ./content/stylesheets/tailwind_base.css -o ./content/stylesheets/tailwind.min.css --minify

      - name: Check Git diff
        run: |
          echo "Please make sure that all Tailwind changes are checked in!"
          git diff --exit-code .

  golangci-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: "Check: golangci-lint"
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.0

  ## TODO: Make a deploy
