name: CoolsterCodes CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "go env GOPATH=$(go env GOPATH)"
          echo "pwd=$(pwd)"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "HOME=${HOME}"

      - name: Clean
        run: make clean

      - name: "Go: Install"
        run: make install

      - name: "Go: Test"
        run: make test

  css:
    runs-on: macos-latest
    env:
      TAILWIND_VERSION: v3.4.15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${{ env.TAILWIND_VERSION }}/tailwindcss-macos-arm64
          mv tailwindcss-macos-arm64 tailwindcss
          chmod +x tailwindcss

      - name: Generate Tailwind
        run: |
          ./tailwindcss -i ./web/stylesheets/tailwind_base.css -o ./web/stylesheets/tailwind.css
          ./tailwindcss -i ./web/stylesheets/tailwind_base.css -o ./web/stylesheets/tailwind.min.css --minify

      - name: Check Git diff
        run: |
          echo "Please make sure that all Tailwind changes are checked in!"
          git diff --exit-code .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: "Check: golangci-lint"
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.0

  deploy_prod:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Go Install
        run: make install

      - name: Build the app
        run: make build
        env:
          TARGET_DIR: ./public
          CC_ENV: prod

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # You can write your Azure CLI inline scripts here.

      - name: Send it
        run: swa deploy ./public --app-name CoolsterCodes --env production --deployment-token ${{ secrets.SWA_TOKEN }}
